-- Tạo database và bảng cho ứng dụng Quiz Online
CREATE DATABASE IF NOT EXISTS quizweb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE quizweb;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  time_limit INT NOT NULL,
  quiz_json LONGTEXT NOT NULL,
  players_json LONGTEXT NOT NULL,
  host_name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  room_code VARCHAR(10) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  quiz_title VARCHAR(255) NOT NULL,
  score INT NOT NULL,
  total INT NOT NULL,
  percent INT NOT NULL,
  completed_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
